stages:
    - image
    - analysis
    - test
    - coverage

########################################################################################################################
# Docker
.image: &image
    stage: image
    before_script:
        - docker info
    script:
        # Login to GitLab container registry https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-gitlab-container-registry
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        # Build image using Docker caching, see https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#making-docker-in-docker-builds-faster-with-docker-layer-caching
        - docker pull "$IMAGE_TAG" || true
        - docker build --cache-from "$IMAGE_TAG" -t "$IMAGE_TAG" "docker/$IMAGE_NAME"
        - docker push "$IMAGE_TAG"
    tags:
        - dind

image:ubuntu:bionic:
    <<: *image
    variables:
        IMAGE_NAME: ubuntu:bionic
        IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME

########################################################################################################################
# Basic declarations
.ubuntu-bionic: &ubuntu-bionic
    image: "$CI_REGISTRY/$CI_PROJECT_PATH/ubuntu:bionic"

.install-dependencies: &install-dependencies
    before_script:
        - pip3 list
        # Install package dependencies
        - cat requirements.txt
        - pip3 install -r requirements.txt $EXTRA_REQUIREMENTS
        - pip3 list

.test: &test
    <<: *install-dependencies
    script:
        - mkdir coverage
        - make test-coverage
    artifacts:
        expire_in: 1d
        paths:
        - coverage/
    variables:
        COVERAGE_FILE: "coverage/.coverage.$CI_BUILD_ID"
        EXTRA_REQUIREMENTS: "-r requirements-dev.txt coverage"

########################################################################################################################
# Individual jobs
isort:
    <<: *ubuntu-bionic
    stage: analysis
    before_script:
        - pip3 install isort
        - pip3 list
    script: "make check-isort"

flake8:
    <<: *ubuntu-bionic
    stage: analysis
    before_script:
        - pip3 install flake8
        - pip3 list
    script: "make check-flake8"

pydocstyle:
    <<: *ubuntu-bionic
    stage: analysis
    before_script:
        - pip3 install pydocstyle
        - pip3 list
    script: "make check-doc"

licensing:
    <<: *ubuntu-bionic
    stage: analysis
    before_script:
        # Set up SSH key for access to gitlab repositories
        - install -m 700 -d $HOME/.ssh
        - install -m 600 $SRC_DIR/{id_rsa,id_rsa.pub,known_hosts} $HOME/.ssh/
        # Clone the licence check
        - git clone git@gitlab.office.nic.cz:internal-tools/license-check.git --single-branch --depth 1
    script:
        - ./license-check/license-check.sh -v
    variables:
        SRC_DIR: /usr/local/env

test:bionic:
    <<: *test
    <<: *ubuntu-bionic

coverage-report:
    <<: *ubuntu-bionic
    stage: coverage
    before_script:
        - pip3 install coverage
        - pip3 list
    script:
        - coverage3 combine coverage/
        - coverage3 report --include=tests.py --fail-under=100
        - coverage3 report --omit=tests.py
